import { useState } from 'react';

import { Avatar } from './Avatar';
import { Comment } from './Comment';
import styles from './Post.module.css';

export function Post({ author, publishedAt, content }) {
	const [comments, setComments] = useState(['Awesome work! ❤️']);
	const [newComment, setNewComment] = useState('');

	const publishedDateFormatted = new Intl.DateTimeFormat('en', {
		day: '2-digit',
		month: 'long',
		hour: '2-digit',
		minute: '2-digit',
	}).format(publishedAt);

	const publishedDateRelativeToNow = new Intl.RelativeTimeFormat('en');

	// when the action is generated by the user
	// functions starts with 'handle' name
	function handleCreateNewComment() {
		event.preventDefault();
		setComments([...comments, newComment]);
		setNewComment('');
	}

	function handleNewCommentChange() {
		setNewComment(event.target.value);
	}

	return (
		<article className={styles.post}>
			<header>
				<div className={styles.author}>
					<Avatar src={author.avatarUrl} />
					<div className={styles.authorInfo}>
						<strong>{author.name}</strong>
						<span>{author.role}</span>
					</div>
				</div>
				<time
					className={styles.time}
					title={publishedDateFormatted}
					dateTime={publishedAt.toISOString()}
				>
					{publishedDateRelativeToNow.format(-1, 'day')}
				</time>
			</header>

			<div className={styles.content}>
				{content.map((line) => {
					if (line.type == 'paragraph') {
						return <p>{line.content}</p>;
					} else if (line.type == 'link') {
						return (
							<p>
								<a href=''>{line.content}</a>
							</p>
						);
					}
				})}
			</div>

			<form
				onSubmit={handleCreateNewComment}
				className={styles.commentForm}
			>
				<strong>Leave a comment</strong>
				<textarea 
					name="comment"
					placeholder='Your comment'
					value={newComment}
					onChange={handleNewCommentChange}
				>
				</textarea>
				<footer>
					<button type='submit'>Submit</button>
				</footer>
			</form>

			<div className={styles.commentList}>
				{comments.map((comment) => {
					return <Comment content={comment} />;
				})}
			</div>
		</article>
	);
}
